container:
  image: debian:buster-slim

build_task:
  prep_script: apt-get update; apt-get -y --no-install-recommends install make
  debian_script: make debian
  compile_script: make
  test_script: make test
  install_script: make install

